name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install pnpm
        run: 
          npm i -g pnpm
      - name: Install dependencies
        run: 
          pnpm i
      - name: Lint
        run:
            pnpm lint
      - name: TSC
        run: 
            pnpm lint:types
      - name: Run tests
        run:
            pnpm test:coverage
      - name: Run e2e tests
        run:
            pnpm test:e2e:ci
      - name: build app
        run: pnpm build
      - name: build storybook
        run: pnpm build-storybook
      - name: Install firebase
        run:
            npm i -g firebase-tools
      - name: Firebase deploy app and storybook
        run: |
          firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token ${{ secrets.FIREBASE_TOKEN }}
      - name: Update code coverage badges and commit badges
        run: 
            pnpm test:coverage:badges
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'master'